# Generated by Django 4.1.3 on 2022-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Management'), ('2', 'Sales'), ('3', 'Support')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
