# Generated by Django 4.1.3 on 2022-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Management'), ('2', 'Sales'), ('3', 'Support')], default='1', max_length=20),
        ),
    ]
