# Generated by Django 4.1.3 on 2022-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Management'), ('2', 'Sales'), ('3', 'Support')], max_length=20),
        ),
    ]
