# Generated by Django 4.1.3 on 2022-12-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_remove_user_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_user', 'Create a new user'),)},
        ),
    ]
