# Generated by Django 4.1.3 on 2022-12-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_user_options_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
