# Generated by Django 4.1.3 on 2022-11-30 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_client_first_name_alter_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='Not completed', max_length=250, verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Client Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Client Date Updated'),
            preserve_default=False,
        ),
    ]
