# Generated by Django 4.1.3 on 2022-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_alter_client_company_name_alter_client_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
