# Generated by Django 4.1.3 on 2022-12-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_contract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('1', 'Incoming'), ('2', 'In progress'), ('3', 'Closed')], max_length=1),
        ),
    ]
