# Generated by Django 4.1.3 on 2022-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_alter_contract_status_alter_event_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
