# Generated by Django 4.1.3 on 2023-01-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0055_alter_contract_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
