# Generated by Django 4.1.3 on 2023-01-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0056_alter_contract_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sales_contact',
        ),
    ]
