# Generated by Django 4.1.3 on 2023-01-04 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0057_remove_contract_sales_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
