# Generated by Django 4.1.3 on 2023-01-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0061_alter_contract_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sales_contact',
        ),
    ]
