# Generated by Django 4.1.3 on 2023-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0063_alter_event_support_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('1', 'Prospect'), ('2', 'Existing')], default='1', max_length=1),
        ),
    ]
