# Generated by Django 4.1.3 on 2023-01-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0064_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
