# Generated by Django 4.1.3 on 2023-01-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0065_remove_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
