# Generated by Django 4.1.3 on 2023-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0069_alter_event_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
