# Generated by Django 4.1.3 on 2023-01-21 21:52

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0073_alter_contract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(validators=[authentication.validators.Validators.check_is_float]),
        ),
    ]
