# Generated by Django 4.1.3 on 2023-01-22 08:19

import CRM.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0075_alter_contract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(validators=[CRM.validators.validate_amount]),
        ),
    ]
