# Generated by Django 4.1.3 on 2023-01-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0081_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.contract'),
        ),
    ]
